### ISSUE TITLE
Parameter: sxsrf

### ISSUE THREAD

**Issue by randomaccess3** [randomaccess3/googleURLParser#7]
New parameter noticed in 2019-09-06

sxsrf=ACYBGNRNuA5dIJmZVIjTPpTjpZTC0hDIOA%3A1567748385001

Run URL decoder over parameter
remove final 3 (millisecond timestamp)
convert Unix timestamp
currently unsure what sets the value

**Comment by alik604** [comment]
What does `sxsrf ` mean?

**Comment by randomaccess3** [comment]
No idea sorry!
Ryan Benson incorporated the decoding into UNFURL

**Comment by nathan3882** [comment]
Cross site request forgery @alik604 perhaps? Unsure about the s. Could be a stamped XSRF / CSRF token?

%3A is an url encoded :
